---
title: "Web scraping with R"
author: "Ana Mamatelashvili"
date: "22/01/2019"
output: html_notebook
---

```{r}
library(rvest)
library(tibble)
library(magrittr)
library(stringr)
library(dplyr)
library(purrr)
library(writexl)
```

```{r}
url_ex <- "https://www.hr.ge/announcement/47787/"
page_ex <- read_html(url_ex) 
page_ex

page_body <- page_ex %>% html_node('body')
page_body
```
## HTML


```{r}
job_title <- page_body %>% 
  html_node(".anncmt-title h1") %>% 
  html_text(trim=T)
job_title
```

```{r}
job_title <- page_body %>% 
  html_node("h1") %>% 
  html_text(trim=T)
job_title
```

```{r}
dates <- page_body %>% 
  html_node(".firm-card:nth-child(1) td") %>% 
  html_text(trim=T)
dates
```


```{r}
page <- read_html("https://www.hr.ge/announcements/of-vacancy")
table_nodes <- page %>% html_nodes(".table.table-hover.vacanc") 

df <- html_table(table_nodes) %>% `[[`(1) 
colnames(df) <- c('ვაკანსია', '2', '3', 'დამსაქმებელი',
                     '4', 'თარიღები_მდებარეობა', '7')

df <- df %>% mutate(თარიღები_მდებარეობა = 
                     თარიღები_მდებარეობა %>% 
                       str_replace('\r\n ', ' ')) %>%
  select(ვაკანსია, დამსაქმებელი, თარიღები_მდებარეობა) 
```

```{r echo = TRUE}
table <- html_table(table_nodes)
table
```

```{r}
page_hrefs <- page %>% 
  html_nodes(".pagination a") %>% 
  html_attr("href") %>% 
  unique()
urls <- paste("https://hr.ge", page_hrefs, sep = "")
urls
```


```{r}
get_urls_hrge <- function(url){
  page <- read_html(url)
  all_urls <- page %>% 
    html_nodes("tr") %>%  
    html_nodes("td") %>% 
    html_node("a") %>% 
    html_attr("href") %>% 
    str_subset("/announcement/") %>% 
    substr(1,19) %>% 
    paste("https://hr.ge", ., sep = "") 
}
ad_urls <- map(urls, get_urls_hrge) %>% unlist() %>% unique()
ad_urls[1:5]
```


```{r}
scrape_hrge <- function(x){
  ad_html <- read_html(x)
  # position title
  A <- ad_html %>% html_nodes(".anncmt-title") %>% 
    html_text(trim = T) %>% as.data.frame(stringsAsFactors = F)
  # employer name
  B <- ad_html %>% html_nodes(".anncmt-customer") %>% 
    html_text(trim = T) %>% as.data.frame(stringsAsFactors = F)
  # text from ad body 
  C <- ad_html %>% html_node(".firm-descr") %>% 
    html_text(trim = TRUE) %>% as.data.frame(stringsAsFactors = F)
  
  df_row <- cbind(A, B, C)
  names(df_row) <- c("ვაკანსია", "დამსაქმებელი", "ვაკანსიის_დეტალები")

  df_row <- as.tibble(df_row)
  return(df_row)  
}

map_df(ad_urls[1:5], scrape_hrge)
```




